server {
    listen 80;
    listen [::]:80;

    server_name 167.99.232.38;

    root /var/www/opslab/html;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:3000/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
